using System;

namespace LibSxS.Delta
{
    [Flags]
    public enum DeltaFileType : ulong
    {
        DELTA_FILE_TYPE_RAW = 0x1,
        DELTA_FILE_TYPE_I386 = 0x2,
        DELTA_FILE_TYPE_IA64 = 0x4,
        DELTA_FILE_TYPE_AMD64 = 0x8,
        DELTA_FILE_TYPE_CLI4_I386 = 0x10,
        DELTA_FILE_TYPE_CLI4_AMD64 = 0x20,
        DELTA_FILE_TYPE_CLI4_ARM = 0x40,
        DELTA_FILE_TYPE_CLI4_ARM64 = 0x80,

        DELTA_FILE_TYPE_SET_EXECUTABLES_1 =
           DELTA_FILE_TYPE_RAW |
           DELTA_FILE_TYPE_I386 |
           DELTA_FILE_TYPE_IA64 |
           DELTA_FILE_TYPE_AMD64,

        DELTA_FILE_TYPE_SET_EXECUTABLES = DELTA_FILE_TYPE_SET_EXECUTABLES_1,

        DELTA_FILE_TYPE_SET_EXECUTABLES_2 =
           DELTA_FILE_TYPE_RAW |
           DELTA_FILE_TYPE_CLI4_I386 |
           DELTA_FILE_TYPE_IA64 |
           DELTA_FILE_TYPE_CLI4_AMD64 |
           DELTA_FILE_TYPE_CLI4_ARM,

        DELTA_FILE_TYPE_SET_EXECUTABLES_3 =
           DELTA_FILE_TYPE_RAW |
           DELTA_FILE_TYPE_CLI4_I386 |
           DELTA_FILE_TYPE_IA64 |
           DELTA_FILE_TYPE_CLI4_AMD64 |
           DELTA_FILE_TYPE_CLI4_ARM |
           DELTA_FILE_TYPE_CLI4_ARM64,

        DELTA_FILE_TYPE_SET_EXECUTABLES_LATEST = DELTA_FILE_TYPE_SET_EXECUTABLES_3
    }
}
