using System;

namespace LibSxS.Delta
{
    [Flags]
    public enum DeltaFlags : ulong
    {
        DELTA_FLAG_NONE = 0x0,
        DELTA_FLAG_E8 = 0x1,
        DELTA_FLAG_MARK = 0x2,
        DELTA_FLAG_IMPORTS = 0x4,
        DELTA_FLAG_EXPORTS = 0x8,
        DELTA_FLAG_RESOURCES = 0x10,
        DELTA_FLAG_RELOCS = 0x20,
        DELTA_FLAG_I386_SMASHLOCK = 0x40,
        DELTA_FLAG_I386_JMPS = 0x80,
        DELTA_FLAG_I386_CALLS = 0x100,
        DELTA_FLAG_AMD64_DISASM = 0x200,
        DELTA_FLAG_AMD64_PDATA = 0x400,
        DELTA_FLAG_IA64_DISASM = 0x800,
        DELTA_FLAG_IA64_PDATA = 0x1000,
        DELTA_FLAG_UNBIND = 0x2000,
        DELTA_FLAG_CLI_DISASM = 0x4000,
        DELTA_FLAG_CLI_METADATA = 0x8000,
        DELTA_FLAG_HEADERS = 0x10000,
        DELTA_FLAG_IGNORE_FILE_SIZE_LIMIT = 0x20000,
        DELTA_FLAG_IGNORE_OPTIONS_SIZE_LIMIT = 0x40000,
        DELTA_FLAG_ARM_DISASM = 0x80000,
        DELTA_FLAG_ARM_PDATA = 0x100000,
        DELTA_FLAG_CLI4_METADATA = 0x200000,
        DELTA_FLAG_CLI4_DISASM = 0x400000,
        DELTA_FLAG_ARM64_DISASM = 0x800000,
        DELTA_FLAG_ARM64_PDATA = 0x1000000,

        DELTA_DEFAULT_FLAGS_RAW = DELTA_FLAG_NONE,

        DELTA_DEFAULT_FLAGS_I386 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_I386_SMASHLOCK |
           DELTA_FLAG_I386_JMPS |
           DELTA_FLAG_I386_CALLS |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI_DISASM |
           DELTA_FLAG_CLI_METADATA,

        DELTA_DEFAULT_FLAGS_IA64 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_IA64_DISASM |
           DELTA_FLAG_IA64_PDATA |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI_DISASM |
           DELTA_FLAG_CLI_METADATA,

        DELTA_DEFAULT_FLAGS_AMD64 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_AMD64_DISASM |
           DELTA_FLAG_AMD64_PDATA |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI_DISASM |
           DELTA_FLAG_CLI_METADATA,

        DELTA_CLI4_FLAGS_I386 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_I386_SMASHLOCK |
           DELTA_FLAG_I386_JMPS |
           DELTA_FLAG_I386_CALLS |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI4_DISASM |
           DELTA_FLAG_CLI4_METADATA,

        DELTA_CLI4_FLAGS_AMD64 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_AMD64_DISASM |
           DELTA_FLAG_AMD64_PDATA |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI4_DISASM |
           DELTA_FLAG_CLI4_METADATA,

        DELTA_CLI4_FLAGS_ARM =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_ARM_DISASM |
           DELTA_FLAG_ARM_PDATA |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI4_DISASM |
           DELTA_FLAG_CLI4_METADATA,

        DELTA_CLI4_FLAGS_ARM64 =
           DELTA_FLAG_MARK |
           DELTA_FLAG_IMPORTS |
           DELTA_FLAG_EXPORTS |
           DELTA_FLAG_RESOURCES |
           DELTA_FLAG_RELOCS |
           DELTA_FLAG_ARM64_DISASM |
           DELTA_FLAG_ARM64_PDATA |
           DELTA_FLAG_UNBIND |
           DELTA_FLAG_CLI4_DISASM |
           DELTA_FLAG_CLI4_METADATA
    }
}
